-- grant USAGE to a database to PUBLIC role
-- we will use this database to demonstrate queries
GRANT USAGE ON DATABASE INGEST_DATA TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA INGEST_DATA.PUBLIC TO ROLE PUBLIC;
GRANT SELECT ON TABLE INGEST_DATA.PUBLIC.TRANSACTIONS TO ROLE PUBLIC;
GRANT SELECT ON TABLE INGEST_DATA.PUBLIC.CUSTOMER TO ROLE PUBLIC;

USE ROLE ACCOUNTADMIN;
-- virtual warehouse for data scientist
CREATE WAREHOUSE DATASCIENCE_WH WITH WAREHOUSE_SIZE = 'SMALL',WAREHOUSE_TYPE='STANDARD' AUTO_SUSPEND=300
AUTO_RESUME=TRUE;

-- virtual warehouse for DBAs. It is sized extra small since DBA queries should normally be of short duration
CREATE WAREHOUSE WAREHOUSE_DBA_WH WITH WAREHOUSE_SIZE = 'XSMALL',WAREHOUSE_TYPE='STANDARD' AUTO_SUSPEND=300
AUTO_RESUME=TRUE;

CREATE ROLE DATA_SCIENTISTS;
GRANT USAGE ON WAREHOUSE DATASCIENCE_WH TO ROLE DATA_SCIENTISTS;

CREATE ROLE DBAS;
GRANT USAGE ON WAREHOUSE DBA_WH TO ROLE DBAS;

-- create a login for data scientist 1 & data scientist 2
CREATE USER DS_1 PASSWORD = 'DS_1' LOGIN_NAME='DS_1' DEFAULT_ROLE='DATA_SCIENTISTS'
DEFAULT_WAREHOUSE='DATASCIENCE_WH' MUST_CHANGE_PASSWORD=FALSE;

CREATE USER DS_2 PASSWORD = 'DS_2' LOGIN_NAME='DS_2' DEFAULT_ROLE='DATA_SCIENTISTS'
DEFAULT_WAREHOUSE='DATASCIENCE_WH' MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE DATA_SCIENTISTS TO USER DS_1;
GRANT ROLE DATA_SCIENTISTS TO USER DS_2;

-- create a login for DBA 1 & DBA 2
CREATE USER DBA_1 PASSWORD = 'DBA_1' LOGIN_NAME='DBA_1' DEFAULT_ROLE='DBAS'
DEFAULT_WAREHOUSE='DATASCIENCE_WH' MUST_CHANGE_PASSWORD=FALSE;

CREATE USER DBA_2 PASSWORD = 'DBA_2' LOGIN_NAME='DBA_2' DEFAULT_ROLE='DBAS'
DEFAULT_WAREHOUSE='DBA_WH' MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE DBAS TO USER DBA_1;
GRANT ROLE DBAS TO USER DBA_2;

-- switch role to ACCOUNTADMIN, see Warehouses

-- Log out

-- Login with DS_1/DS_1, see Warehouses
-- Run SQLs in Worksheets
USE DATABASE INGEST_DATA;
SELECT * FROM CUSTOMER LIMIT 10;

-- Log out

-- Login with DBA_1/DBA_1, see Warehouses
-- Run SQLs in Worksheets
USE DATABASE INGEST_DATA;
SELECT * FROM CUSTOMER LIMIT 20;






